version: '3.4'

services:
    nginx-php-cortex-quizz:
        image: nginx-php:7.4
        build: ./docker
        container_name: nginx-php-cortex-quizz
        working_dir: "/var/www/html/cortex-quizz.cortex-digital.fr"
        healthcheck:
            interval: 10s
            timeout: 3s
            retries: 3
            start_period: 30s
        depends_on:
            - db-cortex-quizz
        volumes:
            - ./:/var/www/html/cortex-quizz.cortex-digital.fr
            - ../cortex-quizz.cortex-digital.doc:/var/www/html/cortex-quizz.cortex-digital.doc
            - ./docker/conf/nginx-site.conf:/etc/nginx/sites-available/default.conf
        ports:
            -   target: 80
                published: 80
                protocol: tcp

    db-cortex-quizz:
        image: mariadb/server:10.4
        container_name: db-cortex-quizz
        environment:
            - MYSQL_ROOT_PASSWORD=cq77
            - MYSQL_DATABASE=cortex-quizz
            - MYSQL_USER=venom
            - MYSQL_PASSWORD=cq77
        volumes:
            - db-data:/var/lib/mysql:rw
        ports:
            -   target: 3306
                published: 3306
                protocol: tcp

    node-cortex-quizz:
      build:
        context: .
        dockerfile: ./docker/Dockerfile-node
      image: nodejs
      container_name: nodejs
      restart: unless-stopped
      ports:
        -   target: 80
            published: 8080
            protocol: tcp
      volumes:
        - .:/home/node/app
        - node_modules:/home/node/app/node_modules

volumes:
    db-data: { }
    node_modules:
